import streamlit as st
import json
import yfinance as yf
import re
import math

# ==============================================================================
# 1. CORE ENGINE: Dynamic Calculation Logic (Refactored Goal)
# ==============================================================================
class SmartCFEngine:
    def __init__(self, ticker, data):
        self.ticker = ticker
        self.events = data.get("events", [])
        self.beta_memory = data.get("beta_memory", 0.0)
        self.extra_iv_str = data.get("extra_iv_str", "")  # For manual IV text appending
        
        # State variables
        self.b = 0.0  # Accumulated Realized P&L
        self.history_logs = []
        self.final_str = ""
        self.original_str = ""
        
        self._process_events()

    def _safe_ln(self, val):
        """Logarithm wrapper to prevent math errors on <= 0"""
        try:
            return math.log(val) if val > 0 else 0.0
        except ValueError:
            return 0.0

    def _process_events(self):
        if not self.events:
            return

        # --- 1. Setup Initial State from First Event ---
        first = self.events[0]
        curr_c = float(first.get("capital", 0))
        # Ref defaults to price if not set
        curr_t = float(first.get("ref", first.get("price"))) 
        # Start Price
        curr_p = float(first.get("price"))
        
        self.original_str = f"ราคาอ้างอิง: {curr_t:.2f}, ทุนคงที่: {curr_c:.0f}"
        
        # --- 2. Iterate through subsequent events ---
        for i, event in enumerate(self.events[1:], start=1):
            next_p = float(event.get("price"))
            next_c = float(event.get("capital", curr_c))
            next_t = float(event.get("ref", curr_t)) 
            
            # THE EQUATION: b += c * ln(P/t) - c' * ln(P/t')
            # term_old: profit generated by old capital moving from old ref to new price
            term_old = curr_c * self._safe_ln(next_p / curr_t)
            # term_new: cost basis adjustment for new capital/ref at new price
            term_new = next_c * self._safe_ln(next_p / next_t)
            
            delta_b = term_old - term_new
            self.b += delta_b
            
            # Generate History Strings (Maintaining exact legacy format)
            # History X: Summary
            hist_str = (
                f"ราคาอ้างอิง: {curr_t} → {next_t}, "
                f"ทุนคงที่: {curr_c} → {next_c} , "
                f"ราคาปัจจุบัน : {next_p}"
            )
            
            # History X.1: Equation Debug
            # Display logic: 2 decimal places for legibility
            eq_debug = (
                f"{self.b - delta_b:.2f} += "
                f"({curr_c} * ln({next_p}/{curr_t})) - "
                f"({next_c} * ln({next_p}/{next_t})) | "
                f"c = {next_c} , t = {next_t} , b = {self.b:.2f}"
            )
            
            self.history_logs.append({
                "summary": hist_str,
                "equation": eq_debug,
                "note": event.get("note", "")
            })
            
            # Update State for next iteration
            curr_c = next_c
            curr_t = next_t
            curr_p = next_p

        # --- 3. Final State Summary ---
        # Format: "Ref, Capital, P&L"
        self.final_str = f"{curr_t}, {curr_c}, {self.b:.2f}"

    def to_legacy_dict(self):
        """Converts internal state to the exact dictionary structure required by existing UI"""
        
        # Calculate EV part for beta_Equation
        # Logic: EV = Net_Memory - Realized_PnL
        # Because Net = Realized + EV  => EV = Net - Realized
        ev_val = self.beta_memory - self.b
        
        # Construct beta_equation string
        # Default format: " Ev: {ev} + Lock_P&L: {b} {extra}"
        beta_eq_str = f" Ev: {ev_val:+.2f} + Lock_P&L: {self.b:+.2f}"
        if self.extra_iv_str:
             beta_eq_str += f" {self.extra_iv_str}"

        res = {
            "ticker": self.ticker,
            "Final": self.final_str,
            "Original": self.original_str,
            "Equation": "b += c · ln(P / t) - c' · ln(P / t'); แล้วตั้ง P = P', t = t', c = c'",
            "comment": " → ".join([e["note"] for e in self.history_logs if e["note"]]),
            "beta_Equation": beta_eq_str,
            "beta_momory": f"Net: {self.beta_memory:+.2f}"
        }
        
        # Inject numbered histories (history_1, history_1.1, etc.)
        for i, log in enumerate(self.history_logs, 1):
            res[f"history_{i}"] = log["summary"]
            res[f"history_{i}.1"] = log["equation"]
            
        return res

# ==============================================================================
# 2. DATA CONFIGURATION (Dynamic Source)
# ==============================================================================
# ข้อมูล Demo จากที่คุณให้มา (แปลงเป็น Event Format) เพื่อให้รันได้ทันทีโดยไม่ต้องสร้างไฟล์ใหม่
DEMO_SMART_DATA = {
    "FFWM": {
        "events": [
            { "price": 6.88, "capital": 1500, "ref": 6.88, "note": "Start" }
        ],
        "beta_memory": -204.00
    },
    "NEGG": {
        "events": [
            { "price": 1.26, "capital": 1500, "ref": 1.26, "note": "T" },
            { "price": 25.2, "capital": 1500, "ref": 25.2, "note": "C" },
            { "price": 25.2, "capital": 1000, "ref": 25.2, "note": "C" },
            { "price": 79.79,"capital": 800,  "ref": 25.2, "note": "C" },
            { "price": 128.09,"capital": 500, "ref": 25.2, "note": "C" },
            { "price": 46.8, "capital": 0.01, "ref": 25.2, "note": "End" }
        ],
        "beta_memory": 1027.28
    },
    "RIVN": {
        "events": [
            { "price": 10.07, "capital": 1500, "ref": 10.07, "note": "Start" },
            { "price": 14.20, "capital": 1500, "ref": 14.20, "note": "T" },
            { "price": 12.00, "capital": 1500, "ref": 12.00, "note": "T" },
            { "price": 16.41, "capital": 4000, "ref": 12.00, "note": "C" }
        ],
        "extra_iv_str": "-438+599+485", # Custom append from your example
        "beta_memory": -686.97
    },
     "APLS": {
        "events": [
            { "price": 39.61, "capital": 1500, "ref": 39.61, "note": "Start" },
            { "price": 24.00, "capital": 2500, "ref": 30.20, "note": "T & C" },
            { "price": 28.50, "capital": 2700, "ref": 28.50, "note": "T" }
        ],
        "beta_memory": -1351.91
    },
    "NVTS": {
        "events": [
            { "price": 3.05, "capital": 1500, "ref": 3.05, "note": "Start" },
            { "price": 8.25, "capital": 1500, "ref": 8.25, "note": "T" },
            { "price": 12.00, "capital": 1500, "ref": 12.00, "note": "T" },
            { "price": 15.76, "capital": 2000, "ref": 12.00, "note": "C" },
            { "price": 10.80, "capital": 2200, "ref": 12.00, "note": "C" }
        ],
        "extra_iv_str": "|+134",
        "beta_memory": 380.83
    },
    # ... สามารถเพิ่มตัวอื่นๆ ได้ใน pattern เดียวกัน ...
}

def load_and_transform_config():
    """Attempts to load smart_cf_config.json, falls back to DEMO_DATA, then transforms to legacy format."""
    raw_data = {}
    
    # 1. Try loading external file
    try:
        with open("smart_cf_config.json", "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except FileNotFoundError:
        # 2. Fallback to Demo Data (so the code works immediately for you)
        # st.warning("ไม่พบไฟล์ 'smart_cf_config.json' - กำลังใช้ข้อมูล Demo ในตัวโค้ด")
        raw_data = DEMO_SMART_DATA

    # 3. Transform using Engine
    legacy_style_config = []
    for ticker, data in raw_data.items():
        engine = SmartCFEngine(ticker, data)
        legacy_style_config.append(engine.to_legacy_dict())
        
    return legacy_style_config

# ==============================================================================
# 3. STREAMLIT APP (UI Preservation Goal)
# ==============================================================================
st.set_page_config(page_title="CF_Graph", page_icon="🔥", layout="wide")

# Load Config via Engine
assets_config = load_and_transform_config()

# --- Everything below this line preserves your EXACT UI Logic ---

tab_names = ["DATA", "Roll_Over" , "All_Ticker" , "Historical_Backtest_CF" , "Call_ratio_spread" , "Extrinsic_Value_(EV)"]  
tabs = st.tabs(tab_names)

current_prices = {}
asset_params = {}

with tabs[1]:
    with st.expander("หลักการ Rollover"):
        st.components.v1.iframe("https://monica.im/share/artifact?id=E9Mg5JX9RaAcfssZsU7K3E", width=1500, height=1000, scrolling=0)

with tabs[2]:
    with st.expander("All_Ticker", expanded=True):
        st.markdown(
        """ 
        กราฟจะยังยึดหลักต้นทุน (อ้างอิง: T_0 , ทุน: C_0 )  ของจุดเริ่มต้นเสมอ
        ไม่ว่าจะ Rollover: T_Reference  , C_Capital  , P_Action ไปกี่ครั้งก็ตาม
        
        EV (Extrinsic Value) = Premium - (ราคาหุ้น - Strike)
        P&L สุทธิ = กำไรจากราคาหุ้น (b) ปกติ -  net_EV  ( EV ใหม่ - EV เก่า)
        """ )        
        st.components.v1.iframe("https://monica.im/share/artifact?id=z6iWHpc2rQjTTMriGBbthi", width=1500, height=1000, scrolling=0)

with tabs[3]:
    with st.expander("Historical_Backtest_CF", expanded=True):
        st.components.v1.iframe("https://monica.im/share/artifact?id=DioBCRhLKWgMw2ey5YMRKJ", width=1500, height=1000, scrolling=0)
        with st.expander("Monthly", expanded=False):        
            st.components.v1.iframe("https://monica.im/share/artifact?id=cgYnircvQqM9YUf58VHd8a", width=1500, height=1000, scrolling=0)
        
with tabs[4]:
    with st.expander("3_piecewise_line", expanded=True):
        st.components.v1.iframe("https://monica.im/share/artifact?id=Z3pbuoEskKzxgxAEWqBYwJ", width=1500, height=1000, scrolling=0)
    with st.expander("3_piecewise_line_v1", expanded=False):
        st.components.v1.iframe("https://monica.im/share/artifact?id=t8qKXjs8Aywi3PcTf4pDZM", width=1500, height=1000, scrolling=0)

with tabs[5]:
    with st.expander("Stock_Replacement_P&L_Calculator", expanded=True):
        st.write("https://stockprice-firstnattapon.streamlit.app")
        st.components.v1.iframe("https://monica.im/share/artifact?id=o4ummrnvDbMBYtEZzU5o6Z", width=1500, height=1000, scrolling=0)
        st.components.v1.iframe("https://monica.im/share/artifact/preview?id=bUZu6BZhKCeDGSG7DQ5pWV", width=1500, height=1000, scrolling=0)
    with st.expander("Stock_Replacement_P&L_Calculator_v1", expanded=False):
        st.components.v1.iframe("https://monica.im/share/artifact?id=d8nc2e3fk3a6SAWxL7e6u3", width=1500, height=1000, scrolling=0)

def parse_final_two_numbers(s):
    nums = re.findall(r"[-+]?\d*\.?\d+", str(s))
    a = float(nums[0]) if len(nums) > 0 else 0.0
    b = float(nums[1]) if len(nums) > 1 else 0.0
    return a, b

with tabs[0]:
    st.write("⚙️ ตั้งค่าทั่วไปและประวัติ Asset (Dynamic Engine Active 🚀)")
    with st.expander(f"บันทึก beta_memory_EV"):
        st.components.v1.iframe("https://monica.im/share/artifact?id=atEAAsV4afxJTBq4jTM3YR", width=1500, height=1000, scrolling=0)

    with st.expander(f"pnl_tracking_strategy"):
        st.components.v1.iframe("https://monica.im/share/artifact?id=SAjLJA9EjhwvRPQySBW4A8", width=1500, height=1000, scrolling=0)

        st.markdown(
        """ 
        กราฟจะยังยึดหลักต้นทุน (อ้างอิง: T_0 , ทุน: C_0 )  ของจุดเริ่มต้นเสมอ
        ไม่ว่าจะ Rollover: T_Reference  , C_Capital  , P_Action ไปกี่ครั้งก็ตาม    
        """ )                
        
        st.json({
        "pnl_tracking_strategy": {
        "description": "กลยุทธ์การติดตามกำไรและขาดทุน (P&L) เพื่อประเมินผลการเทรดแต่ละรอบอย่างแม่นยำ",
        "components": [
          {
            "variable_name": "accumulated_realized_pnl",
            "description": "กำไร/ขาดทุนที่เกิดขึ้นจริงสะสมจากอดีต",
            "purpose": "เก็บยอดสะสมจากรอบการเทรดที่ปิดไปแล้ว ไม่นำมาคำนวณในรอบปัจจุบัน",
            "initial_value": -313.79
          },
          {
            "variable_name": "current_unrealized_pnl",
            "description": "กำไร/ขาดทุนที่ยังไม่เกิดขึ้นจริงของรอบปัจจุบัน",
            "purpose": "ใช้ติดตามผลการดำเนินงานของรอบปัจจุบันเท่านั้น โดยจะเริ่มนับจาก 0",
            "formula": "5000 * ln(P / 20.0)",
            "note": "ค่า P คือราคาปัจจุบัน (Price) และ P&L จะเป็น 0 เมื่อ P = 20.0"
          },
          {
            "variable_name": "total_lifetime_pnl",
            "description": "กำไร/ขาดทุนรวมทั้งหมดตั้งแต่เริ่มต้น",
            "purpose": "ใช้สำหรับดูภาพรวมของผลการดำเนินงานทั้งหมด",
            "formula": "accumulated_realized_pnl + current_unrealized_pnl"
          }
        ],
        "summary": "สำหรับการเทรดรอบใหม่ ให้เริ่มนับ P&L ของรอบใหม่จากศูนย์เสมอ ส่วนผลลัพธ์ของรอบเก่าให้เก็บไว้เป็นยอดสะสมแยกต่างหาก วิธีนี้จะทำให้คุณประเมินกลยุทธ์ในแต่ละรอบการเทรดได้อย่างแม่นยำที่สุดครับ"
        }
        })
    
    st.write("---")
    # Loop นี้ยังคงทำงานเหมือนเดิมเป๊ะ เพราะ assets_config ถูกแปลง structure มาแล้ว
    for asset in assets_config:
        ticker = asset.get("ticker", "N/A")
        final_str = asset.get("Final", "N/A")
        
        # เพิ่ม Emoji บอกสถานะ เพื่อให้รู้ว่าตัวไหนคำนวณผ่าน Engine
        engine_indicator = "" # "⚡" if asset.get("beta_momory") else ""

        with st.expander(f"ตั้งค่าและดูประวัติ: {ticker} {engine_indicator} | \"{final_str}\""):
            try:
                final_price, final_fav = parse_final_two_numbers(final_str)
                asset_params[ticker] = {"entry": final_price, "fav": final_fav}
                try:
                    last_price = yf.Ticker(ticker).fast_info.get("lastPrice", final_price)
                except Exception:
                    st.warning(f"ไม่สามารถดึงราคาล่าสุดของ {ticker} ได้, ใช้ราคา Final แทน")
                    last_price = final_price
                current_prices[ticker] = st.number_input("ราคาปัจจุบัน (สำหรับคำนวณ)", step=0.01, value=float(last_price), key=f"price_{ticker}")
                st.write("---")
                
                # แสดง JSON เหมือนเดิมทุกประการ
                st.write("ข้อมูลดิบจาก Config (Calculated):")
                st.json(asset)
            except Exception as e:
                st.error(f"ข้อมูลใน config ของ {ticker} ผิดพลาด: {e}")
                asset_params[ticker] = {"entry": 0.0, "fav": 0.0}
                current_prices[ticker] = 0.0
